### ISSUE TITLE
숫자가 아닌 문자를 입력하면 뻗습니다.

### ISSUE THREAD

**Issue by eddychin** [segoist43/BinDec#1]
문자를 프로그램 실행 직후에 입력할 때는 괜찮은데(프로그램이 꺼짐) 한 번 숫자 입력 후 두번째 입력부터는 이전 계산 결과가 반복 호출됨

예외나 변수의 초기화가 필요할 것 같아엿

![image](https://cloud.githubusercontent.com/assets/7954595/8799717/11e577ac-2fe7-11e5-828f-027703269ac1.png)

**Comment by strixqlater** [comment]
프로그램 실행 직후에도 문자를 넣으면 이렇게 뜹니다.

프로그램이 꺼지는게 아니라....

아무래도 고치는데 좀 걸리긴 하겠지만, 앞에 명시했잖아요ㅠㅠ

정수를 입력하라고, 전 문자 넣으란 소리 안했단 말입니다!

![capture](https://cloud.githubusercontent.com/assets/9658336/8816800/659e7d10-3066-11e5-8efb-6cc918bb2286.PNG)

**Comment by HDNua** [comment]
문자를 넣었을 때 강제 종료하도록 프로그램 수정하였습니다.
read_int32가 문자열-정수 간 변환을 실패하면 0을 반환함을 이용합니다.
