### ISSUE TITLE
유효범위 이슈

### ISSUE THREAD

**Issue by eddychin** [segoist43/BinDec#2]
`-32768` 미만, `32767` 초과 숫자를 입력하면 프로그램이 틀린 값을 도출합니다.

**Comment by strixqlater** [comment]
애초에 그렇게 높은 값을 변환하는 사람이 있을까요 (...)

불만이시면 직접 커밋 하시져!

**Comment by strixqlater** [comment]
어쨋거나 해결했습니다.

https://github.com/segoist43/BinDec/commit/f9cffd800295662cd85aeb44d1bc45f17ccde08b

**Comment by HDNua** [comment]
segoist43님.

이슈라는 것은 프로그램에서 발생하는 문제를 말하는 것이고, 유효범위는 상당히 중요한 이슈입니다. 범위에 맞지 않는 값을 입력할 사람이 있느냐 없느냐의 문제가 아닙니다. 문제가 발생할 수 있다면 개발자는 해결해야 합니다. 이 범위는 입력할 수 없다고 말하던지요.

자신이 만든 프로그램에 문제가 발생했음을 사용자가 이 정도로 정확하게 알려주는 건 흔하지 않습니다. kdzlvaids님은 segoist43님께 정확하고 유용한 정보를 드렸는데, 이에 대한 segoist43님의 대응은 적절하다고 보기 어렵네요. 불만이시면 직접 커밋하시라니. 이건 segoist43님이 게임을 만들었고 사용자가 게임을 하다가 모종의 이유로 강제 종료했을 때, 사용자가 프로그래밍을 배워서 게임을 수정하라고 말하는 것과 똑같습니다.
그렇게 높은 값을 변환하는 사람이 있겠느냐고 하셨는데, 애초에 이 프로그램을 쓸 사람은 있을까요? 이진수 변환은 검색만 하면 이거보다 멋진 프로그램이 수도 없이 나옵니다.

git 사용법을 배우면서 프로젝트에 기여해볼 생각으로 참여했는데, 굉장히 유감입니다.

**Comment by strixqlater** [comment]
오해의 소지가 있어서 말합니다.

kdzlvaids님과는 저와 개인적인 친분이 있는 분입니다. 그래서 이슈에 있는 코멘트만 저렇게 장난식으로 적었지 실제로는 저 이슈 받고서는 2시간 정도 코드랑 씨름했습니다.

코딩이 장난이냐고 물으시면 전 할 말 없습니다만...

물론 실제로 개인사용자용 프로그램을 만들게 될때는 저런 마인드가 문제가 되겠지만, 그저 배우면서 던지는 농담 한마디씩은 괜찮다고 봅니다.

**Comment by HDNua** [comment]
확인했습니다. 전혀 모르는 사이인줄 알았는데 서로 친분이 있는 사이였군요. 제가 오해했네요.
친한 사이끼리 농담하는 것에는 저도 특별히 문제라고 생각하지 않습니다.

**Comment by eddychin** [comment]
이슈 해결되었으면 닫아주세요..
Edit: 이미 닫혀 있었네요. 코멘트가 달리기에 아직 열려있는 줄 알았습니다.

**Comment by HDNua** [comment]
Closed라고 적혀있는데 아직 닫힌 상태가 아닌 건가요?

**Comment by strixqlater** [comment]
닫힌 상태 맞습니다 ㅋㅋ

뭔가 착각하신듯...싶어요
